// install swagger autojen and swagger ui express
// 1 I create a swagger file
// 2 I will put inside this something to autogenerate my swagger
// 3 Dooc info is like the header of
// 4 I create a swagger in the routes and add the tags
// 5 I run node swagger.js so that  the json can be autogenerated
// 6 Add this to the router router.use("/", require("./swagger"));

// to change to local
// "host": "localhost:3000",
// "basePath": "/",
// "schemes": [
//   "http",
//   "https"
// ],


// "host": "cs341-project2.onrender.com",
// "basePath": "/",
// "schemes": [
//   "https"
// ],

const swaggerAutogen = require("swagger-autogen");
const doc = {
  info: {
    title: "Jose Api",
    description: "cs341 project2",
  },
  host: "localhost:3000",
  schemes: ["http", "https"],
};

const outputFile = './swagger.json';
const endpointFiles = ['./routes/index.js'];

// this will generate swagger.json
swaggerAutogen(outputFile, endpointFiles, doc)
